### ISSUE TITLE
Can't update packages or install anything on DO droplet after running script

### ISSUE THREAD

**Issue by Crazy-Owl** [drew2a/wireguard#22]
Hello, I'm unable to use `apt update` or `apt upgrade` on digital ocean droplet after running the script and setting up everything. 

```
Err:1 http://mirrors.digitalocean.com/ubuntu focal InRelease
  Temporary failure resolving 'mirrors.digitalocean.com'
Err:2 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://mirrors.digitalocean.com/ubuntu focal-updates InRelease
  Temporary failure resolving 'mirrors.digitalocean.com'
Err:4 http://mirrors.digitalocean.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'mirrors.digitalocean.com'

W: Failed to fetch http://mirrors.digitalocean.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'mirrors.digitalocean.com'
W: Failed to fetch http://mirrors.digitalocean.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'mirrors.digitalocean.com'
W: Failed to fetch http://mirrors.digitalocean.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'mirrors.digitalocean.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Also I can't pull or push anything to/from github on my machine when WG tunnel is enabled. I think this has something to do with unbound. What info can I provide to clarify what's going on?

**Comment by drew2a** [comment]
Hi!

> Hello, I'm unable to use apt update or apt upgrade on digital ocean droplet after running the script and setting up everything.

Thank you for reporting, I'll check check it out as soon as I have some free time.

> Also I can't pull or push anything to/from github on my machine when WG tunnel is enabled. I think this has something to do with unbound. What info can I provide to clarify what's going on?

Unbound is a DNS resolver, and it shouldn't affect pull or push to/from GitHub as well as enabled/disabled tunnels.

To ensure that the wireguard tunnel work correct, you can perform these steps:

1. Try to ping 1.1.1.1 (this should prove that your connection is not interrupted)
2. Check your IP with any tool like https://ipinfo.io/  (this should prove that the tunnel work properly)
3. Try to check DNS resolution. The way to do this depends on your OS. The easiest way is just to open a random site in a browser (this should prove that Unbound work properly)

I hope it will help you with the issue.

**Comment by nilcolor** [comment]
Hi,
I tried your awesome script (thank you!) to setup Wireguard on Debian 10 and then Ubuntu 22.04.
Everything went well, no errors. Downloaded client config file.
Wireguard client is able to connect but after that, DNS just stop working on my laptop until WG client disconnected
```
$ ping github.com
ping: cannot resolve github.com: Unknown host
```
The same result is when I install with unbound or without. Any ideas what can be wrong?

**Comment by drew2a** [comment]
@nilcolor thanks for the heads up! I'll go through the scripts this weekend and get back to you after that.

**Comment by nilcolor** [comment]
If this may help, I tried this on DigitalOcean.

**Comment by nilcolor** [comment]
Seems like it's not only DNS... The moment I activate WG tinnel from the laptop - I cannot use internet at all. Here the red arrow point to spike (no ping) in the `gping` output. Immediately after disconnecting WG - everything is back again.
![SCR-20230708-toba](https://github.com/drew2a/wireguard/assets/163602/e43f49c0-185d-4bbd-a3dd-7d7a5f99beb1)

**Comment by nilcolor** [comment]
🤦 looks like the issue was on my side. DPI ((
Sorry, when I tested from location that not "protected" by DPI - everything just works!
