### ISSUE TITLE
Few errors

### ISSUE THREAD

**Issue by LittleTOXA** [drew2a/wireguard#5]
Perquisites: Clean Ubuntu 18.04 / full update, root login.

1. 
./wg-genconf.sh: line 19: route: command not found

2.
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o  -j MASQUERADE
Bad argument `MASQUERADE'
Try `iptables -h' or 'iptables --help' for more information.

3.
Job for unbound.service failed because the control process exited with error code.
See "systemctl status unbound.service" and "journalctl -xe" for details.
Job for unbound.service failed because the control process exited with error code.
See "systemctl status unbound.service" and "journalctl -xe" for details.
invoke-rc.d: initscript unbound, action "start" failed.
● unbound.service - Unbound DNS server
   Loaded: loaded (/lib/systemd/system/unbound.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2020-04-16 14:42:02 CEST; 12ms ago
     Docs: man:unbound(8)
  Process: 10311 ExecStart=/usr/sbin/unbound -d $DAEMON_OPTS (code=exited, status=1/FAILURE)
 Main PID: 10311 (code=exited, status=1/FAILURE)
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for systemd (237-3ubuntu10.39) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3313  100  3313    0     0   3339      0 --:--:-- --:--:-- --:--:--  3336
Removed /etc/systemd/system/multi-user.target.wants/systemd-resolved.service.
Removed /etc/systemd/system/dbus-org.freedesktop.resolve1.service.
Synchronizing state of unbound.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable unbound
Job for unbound.service failed because the control process exited with error code.
See "systemctl status unbound.service" and "journalctl -xe" for details.

**Comment by steve10287** [comment]
Hey, just add eth0 after POSTROUTING -o

**Comment by drew2a** [comment]
@LittleTOXA sorry for the late response. Is the issue still reproducing?

**Comment by drew2a** [comment]
Seems to be fixed.
